# Development stage
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apk --no-cache add git

# Copy package files
COPY package*.json ./


# Install dependencies
RUN npm install --legacy-peer-deps

# Copy application code
COPY . .

# Set environment variables
ENV NODE_ENV=development
ENV VITE_API_URL=http://localhost:5000/api/v1

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
