version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:5.0
    container_name: encriptofy-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      - MONGO_INITDB_DATABASE=encriptofy
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.runCommand({ ping: 1 })'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: encriptofy-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/encriptofy
      - JWT_SECRET=your_jwt_secret_key_here
      - CORS_ORIGIN=http://localhost:3000
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      mongodb:
        condition: service_healthy
    command: sh -c "npm install && npm start"
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: encriptofy-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data_container:
  frontend_node_modules:
  backend_node_modules:

networks:
  default:
    name: encriptofy-network
